name: Mobile Publish Repo dispatch
on:
  push:
    tags:
      - mobile/v*

jobs:
  publish:
    name: Request to deploy the mobile to other repo by generating repository dispatch
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile && yarn run repository-dispatch
        working-directory: scripts/mobile-publish
        env:
          MOBILE_PUBLISH_AUTH_KEY: ${{ secrets.MOBILE_PUBLISH_AUTH_KEY }}
          MOBILE_PUBLISH_OWNER: ${{ secrets.MOBILE_PUBLISH_OWNER }}
          MOBILE_PUBLISH_REPO: ${{ secrets.MOBILE_PUBLISH_REPO }}
